from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime
import io

def generate_medical_pdf(device_id: str, content: str) -> io.BytesIO:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setFillColor(colors.darkblue)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "BioStream Sentinel - Clinical Incident Report")
    
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 70, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(50, height - 85, f"Subject Device: {device_id}")
    
    # Separator
    c.setStrokeColor(colors.gray)
    c.line(50, height - 95, width - 50, height - 95)

    # Content (Text Wrap Logic)
    text_object = c.beginText(50, height - 120)
    text_object.setFont("Helvetica", 11)
    text_object.setLeading(14)
    
    # Simple word wrap for the demo
    words = content.split()
    line = []
    for word in words:
        if text_object.getX() + c.stringWidth(" ".join(line + [word]), "Helvetica", 11) < (width - 100):
            line.append(word)
        else:
            text_object.textLine(" ".join(line))
            line = [word]
    text_object.textLine(" ".join(line))
    
    c.drawText(text_object)
    
    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 30, "CONFIDENTIAL - AUTHORIZED PERSONNEL ONLY")
    c.drawString(50, 20, "Generated by AI Assistant (GPT-4o-mini). Verification required by MD.")
    
    c.save()
    buffer.seek(0)
    return buffer