"""
src/backend/app/services/report.py
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from datetime import datetime
from xml.sax.saxutils import escape
import io

# --- Page Decorations ---

def on_every_page(canvas, doc):
    """
    Combined callback to draw both header and footer on every page.
    SimpleDocTemplate.build() does not accept 'onPage', so we must call
    both add_header and add_footer inside onFirstPage/onLaterPages.
    """
    add_header(canvas, doc)
    add_footer(canvas, doc)

def add_header(canvas, doc):
    """Draws the company logo and contact info on every page."""
    canvas.saveState()
    
    # 1. Simple Logo Placeholder (Blue Cross)
    logo_x, logo_y = doc.leftMargin, doc.pagesize[1] - 60
    canvas.setFillColor(colors.darkblue)
    canvas.rect(logo_x, logo_y, 20, 20, fill=1, stroke=0)
    canvas.setStrokeColor(colors.white)
    canvas.setLineWidth(3)
    canvas.line(logo_x + 10, logo_y + 2, logo_x + 10, logo_y + 18) # Vertical
    canvas.line(logo_x + 2, logo_y + 10, logo_x + 18, logo_y + 10) # Horizontal

    # 2. Company Name & Info
    canvas.setFont('Helvetica-Bold', 16)
    canvas.setFillColor(colors.darkblue)
    canvas.drawString(logo_x + 30, logo_y + 10, "BioStream Sentinel")
    
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(logo_x + 30, logo_y, "Clinical Monitoring Solutions | Confidential")
    canvas.drawString(logo_x + 30, logo_y - 10, f"Report ID: {datetime.now().strftime('%Y%m%d-%H%M%S')}")

    canvas.restoreState()

def add_footer(canvas, doc):
    """Draws the disclaimer and page number on every page."""
    canvas.saveState()
    
    # Horizontal Rule
    canvas.setStrokeColor(colors.lightgrey)
    canvas.setLineWidth(1)
    canvas.line(doc.leftMargin, doc.bottomMargin + 20, doc.pagesize[0] - doc.rightMargin, doc.bottomMargin + 20)
    
    # Disclaimer
    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(colors.grey)
    disclaimer = "CONFIDENTIAL: This report is intended for authorized clinical personnel only. Generated by AI Assistant (GPT-4o-mini); final medical verification is required by a qualified physician."
    canvas.drawCentredString(doc.pagesize[0] / 2, doc.bottomMargin + 10, disclaimer)
    
    # Page Number
    page_num = f"Page {canvas.getPageNumber()}"
    canvas.drawCentredString(doc.pagesize[0] / 2, doc.bottomMargin, page_num)
    
    canvas.restoreState()

# --- Main Generator Function ---

def generate_medical_pdf(device_id: str, content: str) -> io.BytesIO:
    buffer = io.BytesIO()
    
    # Define Document structure with professional margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=50, leftMargin=50,
        topMargin=90, bottomMargin=60
    )

    # Define Styles
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.black,
        spaceAfter=12
    )
    
    metadata_label = ParagraphStyle('MetaLabel', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=10)
    metadata_value = ParagraphStyle('MetaValue', parent=styles['Normal'], fontName='Helvetica', fontSize=10)
    
    # Use a serif font for the body for a formal look, with justified alignment
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=11,
        leading=15,
        alignment=TA_JUSTIFY,
        spaceBefore=6,
        spaceAfter=6
    )

    # Build the "Story" (Content elements)
    story = []

    # 1. Report Title
    story.append(Paragraph("CLINICAL INCIDENT REPORT", title_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.darkblue))
    story.append(Spacer(1, 12))

    # 2. Metadata Table (Clean alignment)
    data = [
        [Paragraph("Subject Device:", metadata_label), Paragraph(device_id, metadata_value)],
        [Paragraph("Date Generated:", metadata_label), Paragraph(datetime.now().strftime('%B %d, %Y, %H:%M:%S'), metadata_value)],
        [Paragraph("Requested By:", metadata_label), Paragraph("Clinical Dashboard User", metadata_value)],
    ]
    t = Table(data, colWidths=[100, 400])
    t.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(t)
    
    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey, dash=[2, 2]))
    story.append(Spacer(1, 12))

    # 3. Body Content
    # Split input text by newlines to create separate, properly spaced paragraphs
    for para_text in content.split('\n'):
        if para_text.strip():
            # IMPORTANT: Escape text to prevent XML errors (e.g., if content has "<" or "&")
            safe_text = escape(para_text)
            story.append(Paragraph(safe_text, body_style))

    # Build the document, applying header/footer to pages
    doc.build(
        story,
        onFirstPage=on_every_page,
        onLaterPages=on_every_page
    )
    
    buffer.seek(0)
    return buffer